name: Bug Report
description: Report a bug or unexpected behavior in the alation-ai-agent-sdk
title: "[Bug] <short summary>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Before You Submit a Bug Report**

        - This SDK is **only supported for Alation Cloud instances**. If you are using **on-prem**, features like `context_tool` or `data_products` are not supported.
        - Please verify the documentation before filing a bug:
          - [Feature Flags](https://github.com/Alation/alation-ai-agent-sdk#feature-flags)
          - [Authentication Guide](https://github.com/Alation/alation-ai-agent-sdk/blob/main/guides/authentication.md)

        ---

  - type: checkboxes
    id: cloud-confirm
    attributes:
      label: Confirm Compatibility
      options:
        - label: I understand this SDK is only supported on Alation Cloud and not on-prem.
          required: true

  - type: input
    id: alation-version
    attributes:
      label: Alation Version
      description: The version of your Alation instance (e.g. 2025.1.2)
      placeholder: "2025.1.2"
    validations:
      required: true

  - type: input
    id: alation-host
    attributes:
      label: Alation Host
      description: From your instance URL (e.g. `aaa` if your URL is `https://mycompany.alationcloud.com`)
      placeholder: "mycompany"
    validations:
      required: true

  - type: dropdown
    id: context-tool-ff
    attributes:
      label: Is the `context_tool` feature flag enabled?
      description: Refer to the [Feature Flags section](https://github.com/Alation/alation-ai-agent-sdk#feature-flags)
      options:
        - "yes"
        - "no"
        - "don't know"
    validations:
      required: true

  - type: dropdown
    id: data-products-ff
    attributes:
      label: Is the `data_products` feature flag enabled?
      description: Refer to the [Feature Flags section](https://github.com/Alation/alation-ai-agent-sdk#feature-flags)
      options:
        - "yes"
        - "no"
        - "don't know"
    validations:
      required: true

  - type: dropdown
    id: auth-type
    attributes:
      label: Auth method used
      description: Refer to the [Authentication Guide](https://github.com/Alation/alation-ai-agent-sdk/blob/main/guides/authentication.md)
      options:
        - "service_account"
        - "user_account"
        - "don't know"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What happened and what you expected
      placeholder: A clear summary of the issue
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce (optional)
      description: Step-by-step to recreate the bug
      placeholder: |
        1. Do this  
        2. Run this  
        3. See this error
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs (optional)
      description: Paste relevant logs (format with triple backticks)
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Upload images that show the issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement
      options:
        - label: I checked the documentation and existing issues before submitting.
          required: true
